#!/usr/bin/env php

<?php
require __DIR__ . '/vendor/autoload.php';


use Symfony\Component\Console\Application;

$application = new Application();

# add our commands
$application->add(new \App\Command\MakeModel());
$application->add(new \App\Command\MakeController());
$application->add(new \App\Command\MakeMiddleware());

$application->run();